AllCops:
  Exclude:
    - 'exercises/**/example.rb'
    - 'bin/*'
Documentation:
  Enabled: false
StringLiterals:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
BlockDelimiters:
  Enabled: true
RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
Metrics/ClassLength:
  Max: 454
AndOr:
  Enabled: true
  EnforcedStyle: conditionals
FormatString:
  Enabled: true
  EnforcedStyle: percent
Lint/RescueException:
  Exclude:
    - 'exericises/**/*_test.rb'
