---
language: ruby
sudo: false
rvm:
- 2.1.2
install:
- gem install minitest --no-document
- gem install rubocop -v 0.36.0 --no-document
script:
- rubocop -fs -D
- bin/executable-tests-check
- make test
- bin/fetch-configlet
- bin/configlet .
