language: ruby

sudo: false # use containers for faster builds

rvm:
  - 2.1.2

install:
  - gem install minitest --no-ri --no-rdoc
  - gem install rubocop -v 0.31.0 --no-ri --no-rdoc

script:
  - rubocop -fs -D
  - bin/executable-tests-check
  - make test
  - bin/fetch-configlet
  - bin/configlet .
